blank_issues_enabled: false
contact_links:
    - name: ğŸ“˜ Documentation on Nextcloud AIO
      url: https://github.com/nextcloud/all-in-one#faq
      about: Please read the docs first before submitting any report or request!
    - name: â›‘ï¸ Questions and support
      url: https://help.nextcloud.com/tag/aio
      about: For questions, support and help
    - name: ğŸ’¡ Suggest a new feature or discuss one
      url:  https://github.com/nextcloud/all-in-one/discussions/categories/ideas
      about: For new feature requests and discussion of existing ones
    - name: ğŸ’¼ Nextcloud Enterprise
      url: https://portal.nextcloud.com/
      about: If you are a Nextcloud Enterprise customer, or need Professional support, so it can be resolved directly by our dedicated engineers more quickly
