{{- if eq .Values.TALK_RECORDING_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: nextcloud-aio-talk-recording
  name: nextcloud-aio-talk-recording
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-talk-recording
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-talk-recording
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-talk-recording-tmpfs0
            - /nextcloud-aio-talk-recording-tmpfs1
          volumeMounts:
            - name: nextcloud-aio-talk-recording-tmpfs1
              mountPath: /nextcloud-aio-talk-recording-tmpfs1
            - name: nextcloud-aio-talk-recording-tmpfs0
              mountPath: /nextcloud-aio-talk-recording-tmpfs0
      containers:
        - env:
            - name: INTERNAL_SECRET
              value: "{{ .Values.TALK_INTERNAL_SECRET }}"
            - name: NC_DOMAIN
              value: "{{ .Values.NC_DOMAIN }}"
            - name: RECORDING_SECRET
              value: "{{ .Values.RECORDING_SECRET }}"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-talk-recording:20230912_084059-latest
          name: nextcloud-aio-talk-recording
          ports:
            - containerPort: 1234
              hostPort: 1234
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: nextcloud-aio-talk-recording-tmpfs0
            - mountPath: /conf
              name: nextcloud-aio-talk-recording-tmpfs1
      volumes:
        - emptyDir: {}
          name: nextcloud-aio-talk-recording-tmpfs0
        - emptyDir: {}
          name: nextcloud-aio-talk-recording-tmpfs1
{{- end }}
