{{- if eq .Values.IMAGINARY_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: nextcloud-aio-imaginary
  name: nextcloud-aio-imaginary
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-imaginary
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-imaginary
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-imaginary-tmpfs0
          volumeMounts:
            - name: nextcloud-aio-imaginary-tmpfs0
              mountPath: /nextcloud-aio-imaginary-tmpfs0
      containers:
        - env:
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-imaginary:20230817_065941-latest
          name: nextcloud-aio-imaginary
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_NICE
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: nextcloud-aio-imaginary-tmpfs0
      volumes:
        - emptyDir: {}
          name: nextcloud-aio-imaginary-tmpfs0
{{- end }}
