apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace "{{ .Values.NAMESPACE }}"
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nextcloud-aio-redis
  name: nextcloud-aio-redis
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace "{{ .Values.NAMESPACE }}"
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nextcloud-aio-redis
    spec:
      initContainers:
        - name: init-volumes
          image: "alpine:3.20"
          command:
            - chmod
            - "777"
            - /nextcloud-aio-redis
          volumeMounts:
            - name: nextcloud-aio-redis
              mountPath: /nextcloud-aio-redis
      containers:
        - env:
            - name: REDIS_HOST_PASSWORD
              value: "{{ .Values.REDIS_PASSWORD }}"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: "nextcloud/aio-redis:20241106_101604"
          name: nextcloud-aio-redis
          ports:
            - containerPort: 6379
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - NET_RAW
            runAsUser: 999
          volumeMounts:
            - mountPath: /data
              name: nextcloud-aio-redis
      volumes:
        - name: nextcloud-aio-redis
          persistentVolumeClaim:
            claimName: nextcloud-aio-redis
