apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: nextcloud-aio-notify-push
  name: nextcloud-aio-notify-push
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-notify-push
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-notify-push
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-nextcloud
          volumeMounts:
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
      containers:
        - env:
            - name: NC_DOMAIN
              value: "{{ .Values.NC_DOMAIN }}"
            - name: NEXTCLOUD_HOST
              value: nextcloud-aio-nextcloud
            - name: POSTGRES_DB
              value: nextcloud_database
            - name: POSTGRES_HOST
              value: nextcloud-aio-database
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.DATABASE_PASSWORD }}"
            - name: POSTGRES_USER
              value: nextcloud
            - name: REDIS_HOST
              value: nextcloud-aio-redis
            - name: REDIS_HOST_PASSWORD
              value: "{{ .Values.REDIS_PASSWORD }}"
          image: nextcloud/aio-notify-push:20230912_084059-latest
          name: nextcloud-aio-notify-push
          ports:
            - containerPort: 7867
              hostPort: 7867
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /nextcloud
              name: nextcloud-aio-nextcloud
              readOnly: true
      volumes:
        - name: nextcloud-aio-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud
