{{- if eq .Values.IMAGINARY_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: nextcloud-aio-imaginary
  name: nextcloud-aio-imaginary
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-imaginary
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-imaginary
    spec:
      containers:
        - env:
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-imaginary:20240201_120631-latest
          name: nextcloud-aio-imaginary
          ports:
            - containerPort: 9000
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_NICE
{{- end }}
