apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-nextcloud
  name: nextcloud-aio-nextcloud
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-nextcloud
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-nextcloud
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-nextcloud
            - /nextcloud-aio-nextcloud-trusted-cacerts
          volumeMounts:
            - name: nextcloud-aio-nextcloud-trusted-cacerts
              mountPath: /nextcloud-aio-nextcloud-trusted-cacerts
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
      containers:
        - env:
            - name: SMTP_HOST
              value: "{{ .Values.SMTP_HOST }}"
            - name: SMTP_SECURE
              value: "{{ .Values.SMTP_SECURE }}"
            - name: SMTP_PORT
              value: "{{ .Values.SMTP_PORT }}"
            - name: SMTP_AUTHTYPE
              value: "{{ .Values.SMTP_AUTHTYPE }}"
            - name: SMTP_NAME
              value: "{{ .Values.SMTP_NAME }}"
            - name: SMTP_PASSWORD
              value: "{{ .Values.SMTP_PASSWORD }}"
            - name: MAIL_FROM_ADDRESS
              value: "{{ .Values.MAIL_FROM_ADDRESS }}"
            - name: MAIL_DOMAIN
              value: "{{ .Values.MAIL_DOMAIN }}"
            - name: SUBSCRIPTION_KEY
              value: "{{ .Values.SUBSCRIPTION_KEY }}"
            - name: APPS_ALLOWLIST
              value: "{{ .Values.APPS_ALLOWLIST }}"
            - name: ADDITIONAL_APKS
              value: "{{ .Values.NEXTCLOUD_ADDITIONAL_APKS }}"
            - name: ADDITIONAL_PHP_EXTENSIONS
              value: "{{ .Values.NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS }}"
            - name: ADMIN_PASSWORD
              value: "{{ .Values.NEXTCLOUD_PASSWORD }}"
            - name: ADMIN_USER
              value: admin
            - name: APACHE_PORT
              value: "{{ .Values.APACHE_PORT }}"
            - name: CLAMAV_ENABLED
              value: "{{ .Values.CLAMAV_ENABLED }}"
            - name: CLAMAV_HOST
              value: nextcloud-aio-clamav
            - name: COLLABORA_ENABLED
              value: "{{ .Values.COLLABORA_ENABLED }}"
            - name: COLLABORA_HOST
              value: nextcloud-aio-collabora
            - name: FULLTEXTSEARCH_ENABLED
              value: "{{ .Values.FULLTEXTSEARCH_ENABLED }}"
            - name: FULLTEXTSEARCH_HOST
              value: nextcloud-aio-fulltextsearch
            - name: FULLTEXTSEARCH_PASSWORD
              value: "{{ .Values.FULLTEXTSEARCH_PASSWORD }}"
            - name: IMAGINARY_ENABLED
              value: "{{ .Values.IMAGINARY_ENABLED }}"
            - name: IMAGINARY_HOST
              value: nextcloud-aio-imaginary
            - name: INSTALL_LATEST_MAJOR
              value: "{{ .Values.INSTALL_LATEST_MAJOR }}"
            - name: NC_DOMAIN
              value: "{{ .Values.NC_DOMAIN }}"
            - name: NEXTCLOUD_DATA_DIR
              value: /mnt/ncdata
            - name: ONLYOFFICE_ENABLED
              value: "{{ .Values.ONLYOFFICE_ENABLED }}"
            - name: ONLYOFFICE_HOST
              value: nextcloud-aio-onlyoffice
            - name: ONLYOFFICE_SECRET
              value: "{{ .Values.ONLYOFFICE_SECRET }}"
            - name: OVERWRITEHOST
              value: "{{ .Values.NC_DOMAIN }}"
            - name: OVERWRITEPROTOCOL
              value: https
            - name: PHP_MAX_TIME
              value: "{{ .Values.NEXTCLOUD_MAX_TIME }}"
            - name: PHP_MEMORY_LIMIT
              value: "{{ .Values.NEXTCLOUD_MEMORY_LIMIT }}"
            - name: PHP_UPLOAD_LIMIT
              value: "{{ .Values.NEXTCLOUD_UPLOAD_LIMIT }}"
            - name: POSTGRES_DB
              value: nextcloud_database
            - name: POSTGRES_HOST
              value: nextcloud-aio-database
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.DATABASE_PASSWORD }}"
            - name: POSTGRES_USER
              value: nextcloud
            - name: RECORDING_SECRET
              value: "{{ .Values.RECORDING_SECRET }}"
            - name: REDIS_HOST
              value: nextcloud-aio-redis
            - name: REDIS_HOST_PASSWORD
              value: "{{ .Values.REDIS_PASSWORD }}"
            - name: REMOVE_DISABLED_APPS
              value: "{{ .Values.REMOVE_DISABLED_APPS }}"
            - name: SIGNALING_SECRET
              value: "{{ .Values.SIGNALING_SECRET }}"
            - name: STARTUP_APPS
              value: "{{ .Values.NEXTCLOUD_STARTUP_APPS }}"
            - name: TALK_ENABLED
              value: "{{ .Values.TALK_ENABLED }}"
            - name: TALK_PORT
              value: "{{ .Values.TALK_PORT }}"
            - name: TALK_RECORDING_ENABLED
              value: "{{ .Values.TALK_RECORDING_ENABLED }}"
            - name: TALK_RECORDING_HOST
              value: nextcloud-aio-talk-recording
            - name: TRUSTED_CACERTS_DIR
              value: "{{ .Values.NEXTCLOUD_TRUSTED_CACERTS_DIR }}"
            - name: TURN_SECRET
              value: "{{ .Values.TURN_SECRET }}"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
            - name: UPDATE_NEXTCLOUD_APPS
              value: "{{ .Values.UPDATE_NEXTCLOUD_APPS }}"
          image: nextcloud/aio-nextcloud:20231123_084113-latest
          name: nextcloud-aio-nextcloud
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-aio-nextcloud
            - mountPath: /mnt/ncdata
              name: nextcloud-aio-nextcloud-data
            - mountPath: /usr/local/share/ca-certificates
              name: nextcloud-aio-nextcloud-trusted-cacerts
              readOnly: true
      volumes:
        - name: nextcloud-aio-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud
        - name: nextcloud-aio-nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud-data
        - name: nextcloud-aio-nextcloud-trusted-cacerts
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud-trusted-cacerts
