{{- if eq .Values.CLAMAV_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: nextcloud-aio-clamav
  name: nextcloud-aio-clamav
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-clamav
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-clamav
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-clamav
            - /nextcloud-aio-clamav-tmpfs0
            - /nextcloud-aio-clamav-tmpfs1
            - /nextcloud-aio-clamav-tmpfs2
          volumeMounts:
            - name: nextcloud-aio-clamav-tmpfs2
              mountPath: /nextcloud-aio-clamav-tmpfs2
            - name: nextcloud-aio-clamav-tmpfs1
              mountPath: /nextcloud-aio-clamav-tmpfs1
            - name: nextcloud-aio-clamav-tmpfs0
              mountPath: /nextcloud-aio-clamav-tmpfs0
            - name: nextcloud-aio-clamav
              mountPath: /nextcloud-aio-clamav
      containers:
        - env:
            - name: CLAMD_STARTUP_TIMEOUT
              value: "90"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-clamav:20230728_085937-latest
          name: nextcloud-aio-clamav
          ports:
            - containerPort: 3310
              hostPort: 3310
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/lib/clamav
              name: nextcloud-aio-clamav
            - mountPath: /var/lock
              name: nextcloud-aio-clamav-tmpfs0
            - mountPath: /var/log/clamav
              name: nextcloud-aio-clamav-tmpfs1
            - mountPath: /tmp
              name: nextcloud-aio-clamav-tmpfs2
      volumes:
        - name: nextcloud-aio-clamav
          persistentVolumeClaim:
            claimName: nextcloud-aio-clamav
        - emptyDir: {}
          name: nextcloud-aio-clamav-tmpfs0
        - emptyDir: {}
          name: nextcloud-aio-clamav-tmpfs1
        - emptyDir: {}
          name: nextcloud-aio-clamav-tmpfs2
{{- end }}
