apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: nextcloud-aio-redis
  name: nextcloud-aio-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-redis
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-redis
          volumeMounts:
            - name: nextcloud-aio-redis
              mountPath: /nextcloud-aio-redis
      containers:
        - env:
            - name: REDIS_HOST_PASSWORD
              value: "{{ .Values.REDIS_PASSWORD }}"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-redis:20230613_120442-latest
          name: nextcloud-aio-redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: nextcloud-aio-redis
      volumes:
        - name: nextcloud-aio-redis
          persistentVolumeClaim:
            claimName: nextcloud-aio-redis
