{{- if eq .Values.FULLTEXTSEARCH_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: nextcloud-aio-fulltextsearch
  name: nextcloud-aio-fulltextsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-fulltextsearch
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-fulltextsearch
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-elasticsearch
          volumeMounts:
            - name: nextcloud-aio-elasticsearch
              mountPath: /nextcloud-aio-elasticsearch
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms1024M -Xmx1024M
            - name: POSTGRES_HOST
              value: nextcloud-aio-database
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
            - name: discovery.type
              value: single-node
          image: nextcloud/aio-fulltextsearch:20230606_070951-latest
          name: nextcloud-aio-fulltextsearch
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: nextcloud-aio-elasticsearch
      volumes:
        - name: nextcloud-aio-elasticsearch
          persistentVolumeClaim:
            claimName: nextcloud-aio-elasticsearch
{{- end }}
