apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: nextcloud-aio-database
  name: nextcloud-aio-database
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-database
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-database
    spec:
      initContainers:
        - name: init-subpath
          image: alpine
          command:
            - mkdir
            - "-p"
            - /nextcloud-aio-database/data
            - /nextcloud-aio-database
            - /nextcloud-aio-database-dump
            - /nextcloud-aio-database-tmpfs0
          volumeMounts:
            - name: nextcloud-aio-database-tmpfs0
              mountPath: /nextcloud-aio-database-tmpfs0
            - name: nextcloud-aio-database-dump
              mountPath: /nextcloud-aio-database-dump
            - name: nextcloud-aio-database
              mountPath: /nextcloud-aio-database
        - name: init-volumes
          image: alpine
          command:
            - chown
            - 999:999
            - "-R"
            - /nextcloud-aio-database
            - /nextcloud-aio-database-dump
            - /nextcloud-aio-database-tmpfs0
          volumeMounts:
            - name: nextcloud-aio-database-tmpfs0
              mountPath: /nextcloud-aio-database-tmpfs0
            - name: nextcloud-aio-database-dump
              mountPath: /nextcloud-aio-database-dump
            - name: nextcloud-aio-database
              mountPath: /nextcloud-aio-database
      containers:
        - env:
            - name: PGTZ
              value: "{{ .Values.TIMEZONE }}"
            - name: POSTGRES_DB
              value: nextcloud_database
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.DATABASE_PASSWORD }}"
            - name: POSTGRES_USER
              value: nextcloud
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-postgresql:20230728_085937-latest
          name: nextcloud-aio-database
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: data
              name: nextcloud-aio-database
            - mountPath: /mnt/data
              name: nextcloud-aio-database-dump
            - mountPath: /var/run/postgresql
              name: nextcloud-aio-database-tmpfs0
      terminationGracePeriodSeconds: 1800
      volumes:
        - name: nextcloud-aio-database
          persistentVolumeClaim:
            claimName: nextcloud-aio-database
        - name: nextcloud-aio-database-dump
          persistentVolumeClaim:
            claimName: nextcloud-aio-database-dump
        - emptyDir: {}
          name: nextcloud-aio-database-tmpfs0
