{{- if eq .Values.FULLTEXTSEARCH_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-fulltextsearch
  name: nextcloud-aio-fulltextsearch
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-fulltextsearch
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-fulltextsearch
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-elasticsearch
          volumeMounts:
            - name: nextcloud-aio-elasticsearch
              mountPath: /nextcloud-aio-elasticsearch
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512M -Xmx512M
            - name: FULLTEXTSEARCH_PASSWORD
              value: "{{ .Values.FULLTEXTSEARCH_PASSWORD }}"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
              value: nextcloud-aio
            - name: discovery.type
              value: single-node
            - name: http.port
              value: "9200"
            - name: logger.org.elasticsearch.discovery
              value: WARN
            - name: xpack.license.self_generated.type
              value: basic
            - name: xpack.security.enabled
              value: "false"
          image: nextcloud/aio-fulltextsearch:20231027_071516-latest
          name: nextcloud-aio-fulltextsearch
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: nextcloud-aio-elasticsearch
      volumes:
        - name: nextcloud-aio-elasticsearch
          persistentVolumeClaim:
            claimName: nextcloud-aio-elasticsearch
{{- end }}
