{{- if eq .Values.ONLYOFFICE_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ values.NAMESPACE }}
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: nextcloud-aio-onlyoffice
  name: nextcloud-aio-onlyoffice
  namespace: {{ values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-onlyoffice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ values.NAMESPACE }}
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-onlyoffice
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-onlyoffice
          volumeMounts:
            - name: nextcloud-aio-onlyoffice
              mountPath: /nextcloud-aio-onlyoffice
      containers:
        - env:
            - name: JWT_ENABLED
              value: "true"
            - name: JWT_HEADER
              value: AuthorizationJwt
            - name: JWT_SECRET
              value: "{{ .Values.ONLYOFFICE_SECRET }}"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-onlyoffice:20230728_085937-latest
          name: nextcloud-aio-onlyoffice
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/onlyoffice
              name: nextcloud-aio-onlyoffice
      volumes:
        - name: nextcloud-aio-onlyoffice
          persistentVolumeClaim:
            claimName: nextcloud-aio-onlyoffice
{{- end }}
