apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ values.NAMESPACE }}
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: nextcloud-aio-apache
  name: nextcloud-aio-apache
  namespace: {{ values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-apache
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ values.NAMESPACE }}
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-apache
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-nextcloud
            - /nextcloud-aio-apache
            - /nextcloud-aio-apache-tmpfs0
            - /nextcloud-aio-apache-tmpfs1
            - /nextcloud-aio-apache-tmpfs2
            - /nextcloud-aio-apache-tmpfs3
            - /nextcloud-aio-apache-tmpfs4
          volumeMounts:
            - name: nextcloud-aio-apache-tmpfs4
              mountPath: /nextcloud-aio-apache-tmpfs4
            - name: nextcloud-aio-apache-tmpfs3
              mountPath: /nextcloud-aio-apache-tmpfs3
            - name: nextcloud-aio-apache-tmpfs2
              mountPath: /nextcloud-aio-apache-tmpfs2
            - name: nextcloud-aio-apache-tmpfs1
              mountPath: /nextcloud-aio-apache-tmpfs1
            - name: nextcloud-aio-apache-tmpfs0
              mountPath: /nextcloud-aio-apache-tmpfs0
            - name: nextcloud-aio-apache
              mountPath: /nextcloud-aio-apache
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
      containers:
        - env:
            - name: APACHE_MAX_SIZE
              value: "{{ .Values.APACHE_MAX_SIZE }}"
            - name: APACHE_MAX_TIME
              value: "{{ .Values.NEXTCLOUD_MAX_TIME }}"
            - name: APACHE_PORT
              value: "{{ .Values.APACHE_PORT }}"
            - name: COLLABORA_HOST
              value: nextcloud-aio-collabora
            - name: NC_DOMAIN
              value: "{{ .Values.NC_DOMAIN }}"
            - name: NEXTCLOUD_HOST
              value: nextcloud-aio-nextcloud
            - name: NOTIFY_PUSH_HOST
              value: nextcloud-aio-notify-push
            - name: ONLYOFFICE_HOST
              value: nextcloud-aio-onlyoffice
            - name: TALK_HOST
              value: nextcloud-aio-talk
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-apache:20230720_134150-latest
          name: nextcloud-aio-apache
          ports:
            - containerPort: {{ .Values.APACHE_PORT }}
              hostPort: {{ .Values.APACHE_PORT }}
              protocol: TCP
            - containerPort: {{ .Values.APACHE_PORT }}
              hostPort: {{ .Values.APACHE_PORT }}
              protocol: UDP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-aio-nextcloud
              readOnly: true
            - mountPath: /mnt/data
              name: nextcloud-aio-apache
            - mountPath: /var/log/supervisord
              name: nextcloud-aio-apache-tmpfs0
            - mountPath: /var/run/supervisord
              name: nextcloud-aio-apache-tmpfs1
            - mountPath: /usr/local/apache2/logs
              name: nextcloud-aio-apache-tmpfs2
            - mountPath: /tmp
              name: nextcloud-aio-apache-tmpfs3
            - mountPath: /home/www-data
              name: nextcloud-aio-apache-tmpfs4
      volumes:
        - name: nextcloud-aio-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud
        - name: nextcloud-aio-apache
          persistentVolumeClaim:
            claimName: nextcloud-aio-apache
        - emptyDir: {}
          name: nextcloud-aio-apache-tmpfs0
        - emptyDir: {}
          name: nextcloud-aio-apache-tmpfs1
        - emptyDir: {}
          name: nextcloud-aio-apache-tmpfs2
        - emptyDir: {}
          name: nextcloud-aio-apache-tmpfs3
        - emptyDir: {}
          name: nextcloud-aio-apache-tmpfs4
