{{- if eq .Values.TALK_RECORDING_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: nextcloud-aio-talk-recording
  name: nextcloud-aio-talk-recording
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-talk-recording
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-talk-recording
    spec:
      containers:
        - env:
            - name: INTERNAL_SECRET
              value: "{{ .Values.TALK_INTERNAL_SECRET }}"
            - name: NC_DOMAIN
              value: "{{ .Values.NC_DOMAIN }}"
            - name: RECORDING_SECRET
              value: "{{ .Values.RECORDING_SECRET }}"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-talk-recording:20230613_120442-latest
          name: nextcloud-aio-talk-recording
          ports:
            - containerPort: 1234
{{- end }}
