apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace "{{ .Values.NAMESPACE }}"
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: nextcloud-aio-apache
  name: nextcloud-aio-apache
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-apache
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace "{{ .Values.NAMESPACE }}"
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-apache
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-nextcloud
            - /nextcloud-aio-apache
          volumeMounts:
            - name: nextcloud-aio-apache
              mountPath: /nextcloud-aio-apache
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
      containers:
        - env:
            - name: ADDITIONAL_TRUSTED_DOMAIN
              value: "{{ .Values.ADDITIONAL_TRUSTED_DOMAIN }}"
            - name: APACHE_MAX_SIZE
              value: "{{ .Values.APACHE_MAX_SIZE }}"
            - name: APACHE_MAX_TIME
              value: "{{ .Values.NEXTCLOUD_MAX_TIME }}"
            - name: APACHE_PORT
              value: "{{ .Values.APACHE_PORT }}"
            - name: COLLABORA_HOST
              value: nextcloud-aio-collabora
            - name: NC_DOMAIN
              value: "{{ .Values.NC_DOMAIN }}"
            - name: NEXTCLOUD_HOST
              value: nextcloud-aio-nextcloud
            - name: NOTIFY_PUSH_HOST
              value: nextcloud-aio-notify-push
            - name: ONLYOFFICE_HOST
              value: nextcloud-aio-onlyoffice
            - name: TALK_HOST
              value: nextcloud-aio-talk
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-apache:20240228_172209-latest
          name: nextcloud-aio-apache
          ports:
            - containerPort: {{ .Values.APACHE_PORT }}
              protocol: TCP
            - containerPort: {{ .Values.APACHE_PORT }}
              protocol: UDP
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-aio-nextcloud
              readOnly: true
            - mountPath: /mnt/data
              name: nextcloud-aio-apache
      volumes:
        - name: nextcloud-aio-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud
        - name: nextcloud-aio-apache
          persistentVolumeClaim:
            claimName: nextcloud-aio-apache
