{{- if eq .Values.CLAMAV_ENABLED "yes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-clamav
  name: nextcloud-aio-clamav
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-clamav
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-clamav
    spec:
      initContainers:
        - name: init-subpath
          image: alpine
          command:
            - mkdir
            - "-p"
            - /nextcloud-aio-clamav/data
            - /nextcloud-aio-clamav
          volumeMounts:
            - name: nextcloud-aio-clamav
              mountPath: /nextcloud-aio-clamav
        - name: init-volumes
          image: alpine
          command:
            - chown
            - 100:100
            - "-R"
            - /nextcloud-aio-clamav
          volumeMounts:
            - name: nextcloud-aio-clamav
              mountPath: /nextcloud-aio-clamav
      containers:
        - env:
            - name: CLAMD_STARTUP_TIMEOUT
              value: "90"
            - name: TZ
              value: "{{ .Values.TIMEZONE }}"
          image: nextcloud/aio-clamav:20231123_084113-latest
          name: nextcloud-aio-clamav
          ports:
            - containerPort: 3310
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/clamav
              subPath: data
              name: nextcloud-aio-clamav
      volumes:
        - name: nextcloud-aio-clamav
          persistentVolumeClaim:
            claimName: nextcloud-aio-clamav
{{- end }}
