name: Create Psalm Container

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    name: Create Psalm Container

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        run: |
          git clone https://github.com/psalm/psalm-github-actions.git
      
      - name: Modify the Dockerfile
        run: |
          set -x
          sed -i 's|FROM php:7.4-alpine|FROM php:8.1-alpine|' "psalm-github-actions/Dockerfile"
          cat << APCU >> "psalm-github-actions/Dockerfile"
          RUN mkdir -p /usr/src/php/ext/apcu && \
            curl -fsSL https://pecl.php.net/get/apcu | tar xvz -C "/usr/src/php/ext/apcu" --strip 1 && \
            docker-php-ext-install apcu
          APCU

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: 'psalm-github-actions'
          file: 'psalm-github-actions/Dockerfile'
          tags: |
            ghcr.io/nextcloud/all-in-one-psalm:latest
