name: imaginary-update

on:
  workflow_dispatch:
  schedule:
  - cron:  '00 12 * * *'

jobs:
  run_update:
    name: update to latest imaginary commit on master branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Run imaginary-update
      run: |
        # Imaginary
        imaginary_version="$(
          git ls-remote https://github.com/h2non/imaginary master \
            | cut -f1 \
            | tail -1
        )"
        sed -i "s|^ENV IMAGINARY_HASH.*$|ENV IMAGINARY_HASH=$imaginary_version|" ./Containers/imaginary/Dockerfile
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
      with:
        commit-message: imaginary-update automated change
        signoff: true
        title: Imaginary update
        body: Automated Imaginary container update
        labels: dependencies, 3. to review
        milestone: next
        branch: imaginary-container-update
