name: PHP Deprecation Detector
# See https://github.com/wapmorgan/PhpDeprecationDetector

on:
  pull_request:
    paths:
      - 'php/**'
  push:
    branches:
      - main
    paths:
      - 'php/**'

jobs:
  phpdd:
    name: PHP Deprecation Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up php
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # v2
        with:
          php-version: 8.4
          extensions: apcu
          coverage: none

      - name: Run script
        run: |
          set -x
          cd php
          composer install
          composer run php-deprecation-detector | tee -i ./phpdd.log
          if grep "Total issues:" ./phpdd.log; then
            exit 1
          fi
