name: Twig Lint

on:
  pull_request:
    paths:
      - '**.twig'
  push:
    branches:
      - main
    paths:
      - '**.twig'

permissions:
  contents: read

concurrency:
  group: lint-twig-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  twig-lint:
    runs-on: ubuntu-latest
    name: twig-lint

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@7bf05c6b704e0b9bfee22300130a31b5ea68d593 # v2
        with:
          php-version: 8.4
          extensions: apcu
          coverage: none

      - name: twig lint
        run: |
          cd php
          composer install
          composer run lint:twig
