name: Twig Lint

on:
  pull_request:
    paths:
      - '**.twig'
  push:
    branches:
      - main
    paths:
      - '**.twig'

permissions:
  contents: read

concurrency: 
  group: lint-twig-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  twig-lint:
    runs-on: ubuntu-latest
    name: twig-lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: apcu
          coverage: none

      - name: twig lint
        run: |
          cd php
          composer require sserbin/twig-linter:@dev --no-progress --dev
          composer install
          chmod +x ./vendor/bin/twig-linter
          ./vendor/bin/twig-linter lint ./templates
